name: pypsa-env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311hee9e2a2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py311hee243d0_0
  - blosc=1.21.6=h7dd00d9_1
  - bottleneck=1.6.0=np2py311hda5b4d7_3
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.22.0=hb83781b_1
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - cftime=1.6.4=py311h8b6d4dd_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cpython=3.11.14=py311hd8ed1ab_2
  - cryptography=46.0.3=py311h50dcd70_1
  - cycler=0.12.1=pyhcf101f3_2
  - dask-core=2025.12.0=pyhcf101f3_1
  - debugpy=1.8.19=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - executing=2.2.1=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - freexl=2.0.0=h3ab3353_2
  - frozenlist=1.7.0=py311h8740443_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.14.1=h5afe852_0
  - giflib=5.2.2=h93a5062_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-auth=2.45.0=pyhd8ed1ab_0
  - google-cloud-core=2.5.0=pyhd8ed1ab_0
  - google-cloud-storage=3.7.0=pyhcf101f3_0
  - google-crc32c=1.8.0=py311h62e584b_0
  - google-resumable-media=2.8.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - grpcio=1.74.1=py311h9b0a9de_1
  - grpcio-status=1.74.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_hd3baa01_104
  - highspy=1.12.0=np2py311h76ff34e_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - legacy-cgi=2.6.4=pyhcf101f3_0
  - lerc=4.0.0=hd64df32_1
  - levenshtein=0.27.3=py311h251fd82_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libarchive=3.8.2=gpl_h46575ef_100
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgdal-core=3.12.1=ha937536_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgrpc=1.74.1=h3063b79_1
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - libjxl=0.11.1=h3dcb153_5
  - libkml=1.3.0=hc33e383_1022
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnetcdf=4.9.3=nompi_h80c4520_103
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=6.31.1=h98f38fd_4
  - libre2-11=2025.11.05=h91c62da_0
  - librttopo=1.1.0=ha909e78_20
  - libsodium=1.0.20=h99b78c6_0
  - libspatialite=5.1.0=gpl_ha239c29_119
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libxml2-devel=2.15.1=h8d039ee_1
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - linopy=0.5.8=pyhd8ed1ab_1
  - llvm-openmp=21.1.8=h4a912ad_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=hff1a8ea_0
  - multidict=6.7.0=py311h97ccca8_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h11e0b38_0
  - narwhals=2.14.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.3=nompi_py311h8c26f9d_100
  - networkx=3.6.1=pyhcf101f3_0
  - numexpr=2.14.1=py311h5890ad2_1
  - numpy=2.4.0=py311had1e860_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_2
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py311hb52a7e5_2
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - polars=1.36.1=pyh6a1acc5_0
  - polars-runtime-32=1.36.1=py310h34bb384_0
  - proj=9.7.1=h46dec42_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h4921393_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - protobuf=6.31.1=py311h93f9908_2
  - psutil=7.2.1=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.12.1=py311h336326a_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.7.2=py311h55f0a08_2
  - pypsa=1.0.6=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py311h94e639b_10
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - rapidfuzz=3.14.3=py311h251fd82_1
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h46df422_0
  - requests=2.32.5=pyhcf101f3_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.8.0=np2py311hf1dd2ad_1
  - scipy=1.16.3=py311ha71c161_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py311hd4fb369_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.1=h85ec8f2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h09efe57_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h9408147_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h9408147_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - validators=0.35.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xerces-c=3.3.0=h25f632f_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/pypsa-env
